src/objects/IRD_Incident__c.object
<CustomObject>
    <description>Incident object to be used as part of the &quot;Incident Reporting and Dashboard&quot; application.</description>
    <fields>
        <fullName>Assignment_Group__c</fullName>
        <label>Assignment Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opened__c</fullName>
        <label>Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opened_by__c</fullName>
        <label>Opened by</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_By__c</fullName>
        <label>Resolved By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_Date__c</fullName>
        <label>Resolved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting User Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>1 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <label>Incident Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_IRDIncidentListCtrl.cls
public with sharing class Husky_IRDIncidentListCtrl {

    private List<String> incidentIds;
    private String retUrl;

	public Husky_IRDIncidentListCtrl() {
        incidentIds = ApexPages.currentPage().getParameters().get('idSet').split(',');
        retUrl = ApexPages.currentPage().getParameters().get('retURL');
    }

    public List<IRD_Incident__c> incidentList {
        get {
            try {
                if(incidentList == null || incidentList.isEmpty()) {
                    incidentList = [SELECT Id, Name, Assignment_Group__c,
                    	Opened_By__c, State__c, Urgency__c, Priority__c,
                    	Opened__c, Category__c, Short_Description__c,
                    	Hyper_Link__c, Resolved_By__c, Resolved_Date__c
			            FROM IRD_Incident__c
			            Where Id In :incidentIds];
                }
                return incidentList;
            } catch (QueryException ex) {
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
                return null;
            }
        }
        private set;
    }
}