src/objects/IRD_Incident__c.object
<CustomObject>
    <description>Incident object to be used as part of the &quot;Incident Reporting and Dashboard&quot; application.</description>
    <fields>
        <fullName>Assigned_to__c</fullName>
        <label>Assigned to</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assignment_Group__c</fullName>
        <label>Assignment Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller__c</fullName>
        <label>Caller</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <label>Case Type</label>
        <picklist>
            <picklistValues>
                <fullName>Incident</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Request</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Caused_By_Change__c</fullName>
        <label>Caused By Change</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Configuration_Item__c</fullName>
        <label>Configuration Item</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <picklist>
            <picklistValues>
                <fullName>1 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opened__c</fullName>
        <label>Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opened_by__c</fullName>
        <label>Opened by</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_for__c</fullName>
        <label>Requested for</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_By__c</fullName>
        <label>Resolved By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Resolved_Date__c</fullName>
        <label>Resolved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Self Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lync IM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web/Self Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Service Desk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>scm_support</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Problem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Parts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting User Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Corporate Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desktop Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audio/Visual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desktop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Laptop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Peripheral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Server</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Firewall/IDS/IPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Port</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Router</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Switch/Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VPN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Access Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DB2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSSQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sybase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conference Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desk Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOIP Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Device</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investigation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>1 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <label>Incident Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_IRDIncidentService.cls
global class Husky_IRDIncidentService {
	/************************* SOAP Interface ************************************/
	global class APIIncident {
      webservice String inc_number {get; set;}
      webservice String assignment_group {get; set;}
      webservice String assigned_to {get; set;}
      webservice String caller {get; set;}
      webservice String category {get; set;}
      webservice String caused_by_change {get; set;}
      webservice String configuration_item {get; set;}
      webservice String impact {get; set;}
      webservice String location {get; set;}
      webservice Datetime opened {get; set;}
      webservice String openedby {get; set;}
      webservice String priority {get; set;}
      webservice String requested_for {get; set;}
      webservice String resolved_by {get; set;}
      webservice String resolved_date {get; set;}
      webservice String short_description {get; set;}
      webservice String source {get; set;}
      webservice String state {get; set;}
      webservice String subcategory {get; set;}
      webservice String urgency {get; set;}
      webservice String case_type {get; set;}
      webservice String url {get; set;}
    }

    webservice static Husky_ServiceNowApiUtils.Response pushRecords (List<APIIncident> records) {
      Husky_ServiceNowApiUtils.Response response = new Husky_ServiceNowApiUtils.Response();
      initialize();
      response.addResults(parseRecords(records));
      response.addResults(commitRecords());
      return response;
    }
    /*****************************************************************************/

    private static List<IRD_Incident__c> incidentRecords;

    private static void initialize() {
      incidentRecords = new List<IRD_Incident__c>();
    }

    private static List<Husky_ServiceNowApiUtils.Result> parseRecords(List<APIIncident> records) {
	    List<Husky_ServiceNowApiUtils.Result> results = new List<Husky_ServiceNowApiUtils.Result>();

	  	try{ 
			for(APIIncident record : records) {
				IRD_Incident__c incident = new IRD_Incident__c();
				incident.Name = record.inc_number;
				incident.Assignment_Group__c = record.assignment_group;
				incident.Assigned_To__c = record.assigned_to;
				incident.Caller__c = record.caller;
				incident.Category__c = record.category;
				incident.Caused_By_Change__c = record.caused_by_change;
				incident.Configuration_Item__c = record.configuration_item;
				incident.Impact__c = record.impact;
				incident.Location__c = record.location;
				incident.Opened__c = record.opened;
				incident.Opened_By__c = record.openedby;
				incident.Priority__c = record.priority;
				incident.Requested_For__c = record.requested_for;
				incident.Resolved_By__c = record.resolved_by;
				incident.Resolved_Date__c = (!String.isEmpty(record.resolved_Date)) ? 
					getDate(record.resolved_Date) : null;
				incident.Short_Description__c = record.short_description;
				incident.Source__c = record.source;
				incident.State__c = record.state;
				incident.Subcategory__c = record.subcategory;
				incident.Urgency__c = record.urgency;
				incident.Case_Type__c = record.case_type == null ? 'Incident' : record.case_type;
				incident.Hyper_link__c = record.url;
				incidentRecords.add(incident);
			}
	    } catch (Exception ex) {
			String statusCode = Husky_ServiceNowApiUtils.STATUS_ERROR_PARSE;
			Husky_ServiceNowApiUtils.Result result = new Husky_ServiceNowApiUtils.Result(false, null, 
				false, statusCode);
			result.addError(new Husky_ServiceNowApiUtils.Error(null, ex.getMessage(), null));
			results.add(result);
	    }


	    return results;
	}

	private static List<Husky_ServiceNowApiUtils.Result> commitRecords() {
		List<SObject> dmlRecords = new List<SObject>();
		List<Husky_ServiceNowApiUtils.Result> results = new List<Husky_ServiceNowApiUtils.Result>();
		List<Database.UpsertResult> upsertResults = new List<Database.UpsertResult>();

		//Upsert
		upsertResults.addAll(Database.upsert(incidentRecords, IRD_Incident__c.fields.Name, false));
		dmlRecords.addAll((List<SObject>) incidentRecords);

		for(Integer i=0; i < upsertResults.size(); i++) {
		  Database.UpsertResult upsertResult = upsertResults[i];
		  String statusCode = upsertResult.isSuccess() ? Husky_ServiceNowApiUtils.STATUS_SUCCESS_UPSERT : 
		    Husky_ServiceNowApiUtils.STATUS_ERROR_UPSERT;
		  String idString = (String) dmlRecords[i].get('Name');
		  Husky_ServiceNowApiUtils.Result result = new Husky_ServiceNowApiUtils.Result(upsertResult.isCreated(), idString, 
		    upsertResult.isSuccess(), statusCode);
		  for(Database.Error err : upsertResult.getErrors()) {
		    result.addError(new Husky_ServiceNowApiUtils.Error(err.getFields(), err.getMessage(), err.getStatusCode()));
		  }
		  results.add(result);
		}

		return results;
	}

	private static Datetime getDate(String dateString) {
		Integer year = Integer.valueOf(dateString.substring(0,4));
		Integer month = Integer.valueOf(dateString.substring(4,6));
		Integer day = Integer.valueOf(dateString.substring(6,8));
		Integer hours = Integer.valueOf(dateString.substring(8,10));
		Integer minutes = Integer.valueOf(dateString.substring(10,12));
		Integer seconds = Integer.valueOf(dateString.substring(12,14));
		return Datetime.newInstance(year, month, day, hours, minutes, seconds);
	}
}