src/objects/SCOM_Availability__c.object
<CustomObject>
    <fields>
        <fullName>Server__c</fullName>
        <label>Server</label>
        <referenceTo>SCOM_Server__c</referenceTo>
        <relationshipName>SCOM_Availability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Up</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Down</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Availability</label>
    <nameField>
        <displayFormat>SAN-{000000000}</displayFormat>
        <label>SCOM Availability Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SCOM_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>&quot;short_description&quot; column from the changerequest.csv</description>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SCOM Change Request</label>
    <nameField>
        <label>Change Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCOM_Server__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <description>Column &quot;u_application&quot; from the csv. The name of the application hosted on the Server.</description>
        <label>Applications</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Criticality__c</fullName>
        <description>Column &quot;u_cmdb_criticality&quot; from csv.</description>
        <label>Criticality</label>
        <picklist>
            <picklistValues>
                <fullName>(5) Mission Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) Business Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) Business Important</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Productivity Important</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(1) Non-Critical</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <description>&quot;Used_for&quot; from the csv. The environment the server is used for. Ex. Production, Development etc</description>
        <label>Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System__c</fullName>
        <label>Operating System</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>&quot;short_description&quot; field from the csv</description>
        <label>Short Description</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>System_Created_By__c</fullName>
        <description>Column &quot;sys_created_by&quot; from csv.</description>
        <label>System Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SCOM Server</label>
    <nameField>
        <label>Server Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_SCOMUtilities.cls
public class Husky_SCOMUtilities {
	public static Boolean executeTriggerCode = true;

	public static void TriggerBeforeInsertSCOMChangeRequest(List<SCOM_Change_Request__c> changeRequestList) {
		updateServerOnChangeRequest(changeRequestList);
	}

	public static void TriggerBeforeUpdateSCOMChangeRequest(List<SCOM_Change_Request__c> changeRequestList) {
		updateServerOnChangeRequest(changeRequestList);
	}

	public static void updateServerOnChangeRequest(List<SCOM_Change_Request__c> changeRequestList) {
		
	}

	public static void TriggerAfterInsertSCOMAvailability(List<SCOM_Availability__c> availabilityList) {
		sendNotificationOnMissionCriticalDown(availabilityList, null);
	}

	public static void TriggerAfterUpdateSCOMAvailability(List<SCOM_Availability__c> availabilityList, Map<Id,SCOM_Availability__c> oldMap) {
		sendNotificationOnMissionCriticalDown(availabilityList, oldMap);
	}

	public static void sendNotificationOnMissionCriticalDown(List<SCOM_Availability__c> availabilityList, Map<Id,SCOM_Availability__c> oldMap) {
		Set<Id> serverIds = new Set<Id>();
		Boolean isMissionCriticalServerDown = false;
		Messaging.SingleEmailMessage[] emailList = new Messaging.SingleEmailMessage[]{};

		for(SCOM_Availability__c availability : availabilityList) {
			if(availability.Status__c == 'Down' && (oldMap.get(availability.Id) == null || oldMap.get(availability.Id).Status__c == 'Up')) {
				serverIds.add(availability.Server__c);
			}
		}

		//Compile email body
		for(SCOM_Server__c server : [Select Id, Name, Type__c, Criticality__c, Short_Description__c,
											Applications__c, Environment__c, System_Created_By__c,
											Operating_System__c
									 From SCOM_Server__c
									 Where Id In :serverIds]) {
			if(server.Criticality__c == '(5) Mission Critical') {
				Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
				String messageBodyHtml = '<p>The following mission critical servers are reported as down: </p><br/>';
				email.setSubject('Mission Critical Servers Down: ' + server.Name + ' (' + server.Applications__c + ')');
				email.setToAddresses(new String[] {'shreyas.dhond@huskyenergy.com', 'amit.banerjee@huskyenergy.com'});
				messageBodyHtml += '<table>';
				messageBodyHtml += '<tr><td><a target="SCOM_Server__c" href="https://' + System.URL.getSalesforceBaseUrl().getHost() + '/' + server.Id + '">' + server.Name + '</a>';
				messageBodyHtml += '<tr><td>Applications:</td><td>' + server.Applications__c + '<td/></tr>';
				messageBodyHtml += '<tr><td>Environment:</td><td>' + server.Environment__c + '<td/></tr>';
				messageBodyHtml += '<tr><td>Description:</td><td>' + server.Short_Description__c + '<td/></tr>';
				messageBodyHtml += '<tr><td>Created By:</td><td>' + server.System_Created_By__c + '<td/></tr>';
				messageBodyHtml += '<tr><td>Operating System:</td><td>' + server.Operating_System__c + '<td/></tr>';
				messageBodyHtml += '<table>';
				messageBodyHtml += '<br/><br/><a target="SCOM_Server__c" href="https://' + System.URL.getSalesforceBaseUrl().getHost() + '/apex/Husky_SCOMDashboard">View Dashboard</a>';
				email.setHtmlBody(messageBodyHtml);
				isMissionCriticalServerDown = true;
				emailList.add(email);
			}
		}

		//Create Email
		if(isMissionCriticalServerDown)
			Messaging.sendEmail(emailList);
	}
}