src/objects/SCOM_Application_Status__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Kbase_Article__c</fullName>
        <label>Kbase Article</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>PASS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WARN</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application Status</label>
    <nameField>
        <label>Application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_HeartbeatApplicationStatusCtrl.cls
public with sharing class Husky_HeartbeatApplicationStatusCtrl {

	public List<SCOM_Application_Status__c> applicationStatusList {get; private set;}

	public Husky_HeartbeatApplicationStatusCtrl() {
		initialize();
		populateApplicationStatusList();
	}

	private void initialize() {
		applicationStatusList = new List<SCOM_Application_Status__c>();
	}

	private void populateApplicationStatusList() {
		applicationStatusList = [Select Id, Name, Date__c, Kbase_Article__c,
									    Message__c, Status__c
							     From SCOM_Application_Status__c];
	}
}