src/objects/SCOM_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>&quot;cmdb_ci&quot; from the changerequest.csv</description>
        <label>Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval__c</fullName>
        <description>&quot;approval&quot; column from the changerequest.csv</description>
        <label>Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approvers__c</fullName>
        <description>&quot;u_is_approvers&quot; from the changerequest.csv</description>
        <label>Approvers</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Change_Request_Number__c</fullName>
        <externalId>true</externalId>
        <label>Change Request Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>&quot;end_date&quot; column from changerequest.csv</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hyperlink__c</fullName>
        <description>&quot;change_request_hyperlink&quot; column from changerequest.csv</description>
        <label>Hyperlink</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Reviewers__c</fullName>
        <description>&quot;u_implementation_reviewers&quot; column from the changerequest.csv</description>
        <label>Implementation Reviewers</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opened_At__c</fullName>
        <description>Column &quot;opened_at&quot; from the changerequest.csv.</description>
        <label>Opened At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opened_By__c</fullName>
        <description>Column &quot;opened_by&quot; from the changerequest.csv.</description>
        <label>Opened By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <description>&quot;parent&quot; column from the changerequest.csv</description>
        <label>Parent</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>&quot;priority&quot; column from the changerequest.csv</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Urgent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_By_Date__c</fullName>
        <description>&quot;requested_by_date&quot; column from changerequest.csv</description>
        <label>Requested By Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>&quot;short_description&quot; column from the changerequest.csv</description>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Type__c</fullName>
        <description>&quot;u_source_type&quot; column from changerequest.csv</description>
        <label>Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed Standard Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mode 2 Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>&quot;start_date&quot; column from changerequest.csv</description>
        <label>Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>&quot;State&quot; field from the changerequest.csv.</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placeholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Implementation Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergoing Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergoing Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <description>&quot;urgency&quot; column from changerequest.csv</description>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>1 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SCOM Change Request</label>
    <nameField>
        <label>Change Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCOM_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Avg_Metric_Value__c</fullName>
        <label>Avg Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Metric_Value__c</fullName>
        <label>Current Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>External_Key__c</fullName>
        <externalId>true</externalId>
        <label>External Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Metric_Value__c</fullName>
        <label>Max Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Metric__c</fullName>
        <description>The value being measured with this record.</description>
        <label>Metric</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min_Metric_Value__c</fullName>
        <label>Min Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monitor_Instance__c</fullName>
        <description>The drive on the asset being measured.</description>
        <label>Monitor Instance</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server__c</fullName>
        <label>Server</label>
        <referenceTo>SCOM_Server__c</referenceTo>
        <relationshipName>Performance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Realtime</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Baseline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <displayFormat>SPN-{000000000}</displayFormat>
        <label>SCOM Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SCOM_Server__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <description>Column &quot;u_application&quot; from the csv. The name of the application hosted on the Server.</description>
        <label>Applications</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Criticality__c</fullName>
        <description>Column &quot;u_cmdb_criticality&quot; from csv.</description>
        <label>Criticality</label>
        <picklist>
            <picklistValues>
                <fullName>(5) Mission Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) Business Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) Business Important</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Productivity Important</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(1) Non-Critical</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Environment__c</fullName>
        <description>&quot;Used_for&quot; from the csv. The environment the server is used for. Ex. Production, Development etc</description>
        <label>Environment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <description>External Id for upsert operations from dataloader.</description>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Host_Name__c</fullName>
        <description>Column &quot;host_name&quot; from the csv.</description>
        <label>Host Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <description>Column &quot;manufacturer&quot; from the csv.</description>
        <label>Manufacturer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Id__c</fullName>
        <label>Model Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System_Version__c</fullName>
        <label>Operating System Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operating_System__c</fullName>
        <label>Operating System</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>&quot;short_description&quot; field from the csv</description>
        <label>Short Description</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>System_Created_By__c</fullName>
        <description>Column &quot;sys_created_by&quot; from csv.</description>
        <label>System Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Created_On__c</fullName>
        <description>Column &quot;sys_created_on&quot; from csv.</description>
        <label>System Created On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SCOM Server</label>
    <nameField>
        <label>Server Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_SCOM_TestData.cls
public class Husky_SCOM_TestData {

	public static User createUser() {
		List<Profile> lProfiles = [SELECT Id FROM Profile WHERE Name = 'Standard HOG - General User' LIMIT 1];

        //Test USER
        User oUser = new User();
        oUser.FirstName = 'Test';
        oUser.LastName = 'User';
        oUser.Email = oUser.FirstName.toLowerCase() + '.' + oUser.LastName.toLowerCase() + '@testjschon.com';
        oUser.UserName = oUser.Email;
        oUser.Alias = 'tester';
        oUser.TimeZoneSidKey = 'America/New_York';
        oUser.LocaleSidKey = 'en_US';
        oUser.EmailEncodingKey = 'ISO-8859-1';
        oUser.LanguageLocaleKey='en_US';
        oUser.ProfileId = [SELECT Id FROM Profile WHERE Name = 'Standard HOG - General User'].Id;
        oUser.IsActive = true;
        insert oUser;

		return oUser;
	}

	public static List<SCOM_Server__c> createServers(Integer numOfServers) {
		List<SCOM_Server__c> servers = new List<SCOM_Server__c>();
		if (numOfServers != null && numOfServers > 0) {
			List<Schema.PicklistEntry> criticalities = SCOM_Server__c.Criticality__c.getDescribe().getPicklistValues();
			for (Integer i = 0; i < numOfServers; i++) {
				servers.add(new SCOM_Server__c(Applications__c = 'Test application management_' + i,
												Criticality__c = criticalities.get(Math.mod(i, criticalities.size())).getValue(),
												Data_Center__c = 'Test data center - ' + i,
												Environment__c = 'Production',
												External_Id__c = 'linxubttestrunsrv' + i,
												Host_Name__c = 'linxubttestrunsrv' + i,
												Name = 'linxubttestrunsrv' + i,
												Manufacturer__c = 'Dell',
												Model_Id__c = 'Unknown',
												Operating_System__c = 'Linux Ubuntu Server 15 LTS',
												Operating_System_Version__c = '15.2',
												Short_Description__c = 'Just server instance for testing purpose.',
												System_Created_By__c = 'jschon',
												System_Created_On__c = DateTime.now(),
												Type__c = 'Linux Server'));
			}
		}
		insert servers;
		return servers;
	}

	public static List<SCOM_Performance__c> createPerformanceForServers(List<SCOM_Server__c> servers) {
		List<SCOM_Performance__c> performances = new List<SCOM_Performance__c>();
		Integer counter = 0;
		Integer countLimit = 3;
		for (SCOM_Server__c server : servers) {
			if (counter == countLimit) counter = 0;
			performances.add(generatePerformanceForServer(server,
														Husky_SCOMUtilities.PERFORMANCE_TYPE_REALTIME,
														Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU,
														Husky_SCOMUtilities.PERFORMANCE_UNIT_CPU,
														counter));
			performances.add(generatePerformanceForServer(server,
														Husky_SCOMUtilities.PERFORMANCE_TYPE_REALTIME,
														Husky_SCOMUtilities.PERFORMANCE_METRIC_MEMORY,
														Husky_SCOMUtilities.PERFORMANCE_UNIT_MEMORY,
														counter));
			performances.add(generatePerformanceForServer(server,
														Husky_SCOMUtilities.PERFORMANCE_TYPE_BASELINE,
														Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU,
														Husky_SCOMUtilities.PERFORMANCE_UNIT_CPU,
														counter));
			performances.add(generatePerformanceForServer(server,
														Husky_SCOMUtilities.PERFORMANCE_TYPE_BASELINE,
														Husky_SCOMUtilities.PERFORMANCE_METRIC_MEMORY,
														Husky_SCOMUtilities.PERFORMANCE_UNIT_MEMORY,
														counter));
			System.debug('SERVER: ' + server.Id);
			System.debug(performances.get(performances.size()-4));
			System.debug(performances.get(performances.size()-3));
			System.debug(performances.get(performances.size()-2));
			System.debug(performances.get(performances.size()-1));
			counter += 1;
		}
		insert performances;
		return performances;
	}

	public static SCOM_Performance__c generatePerformanceForServer(SCOM_Server__c server, String type,
															String metric, String unit, Integer counter) {
		String monitorInstance = metric == Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU ? '_Total' : '_self';
		List<Integer> baselineAvg = new List<Integer>{60, 70, 80};
		List<Integer> baselineMax = new List<Integer>{70, 80, 90};
		List<Integer> realtimeCurrent = new List<Integer>{50, 75, 99};
		Integer maxValue = type == Husky_SCOMUtilities.PERFORMANCE_TYPE_BASELINE ? baselineMax.get(counter) : realtimeCurrent.get(counter);
		Integer avgValue = type == Husky_SCOMUtilities.PERFORMANCE_TYPE_BASELINE ? baselineAvg.get(counter) : maxValue;
		return new SCOM_Performance__c(Server__c = server.Id,
										Avg_Metric_Value__c = avgValue,
										Current_Metric_Value__c = 0.0,
										Min_Metric_Value__c = 0.0,
										Max_Metric_Value__c = maxValue,
										External_Key__c = server.Name + '-' + metric + '-' + monitorInstance + '-' + type,
										Metric__c = metric,
										Monitor_Instance__c = monitorInstance,
										Time__c = DateTime.now(),
										Type__c = type,
										Unit__c = unit);
	}

	public static List<SCOM_Change_Request__c> createChangeRequests(Integer numOfChRequests) {
		List<SCOM_Change_Request__c> changeRequests = new List<SCOM_Change_Request__c>();
		List<Schema.PicklistEntry> approvals = SCOM_Change_Request__c.Approval__c.getDescribe().getPicklistValues();
		List<Schema.PicklistEntry> priorities = SCOM_Change_Request__c.Priority__c.getDescribe().getPicklistValues();
		List<Schema.PicklistEntry> sources = SCOM_Change_Request__c.Source_Type__c.getDescribe().getPicklistValues();
		List<Schema.PicklistEntry> states = SCOM_Change_Request__c.State__c.getDescribe().getPicklistValues();
		List<Schema.PicklistEntry> urgencies = SCOM_Change_Request__c.Urgency__c.getDescribe().getPicklistValues();
		for (Integer i = 0; i < numOfChRequests; i++) {
			changeRequests.add(new SCOM_Change_Request__c(Active__c = String.valueOf(Math.mod(i, 2)),
														Application__c = 'Test application management_' + i,
														Approval__c = approvals.get(Math.mod(i, approvals.size())).getValue(),
														Approvers__c = 'jschon',
														Change_Request_Number__c = 'CHG000' + i,
														End_Date__c = DateTime.now(),
														Hyperlink__c = 'www.google.com',
														// Implementation_Reviewers__c = '',
														Opened_At__c = DateTime.now()-1,
														Opened_By__c = 'jschon',
														Parent__c = 'RLSE000' + i,
														Priority__c = priorities.get(Math.mod(i, priorities.size())).getValue(),
														// Project__c = '',
														Requested_By_Date__c = DateTime.now(),
														Short_Description__c = 'Test change request ' + i,
														Source_Type__c = sources.get(Math.mod(i, sources.size())).getValue(),
														Start_Date__c = DateTime.now(),
														State__c = states.get(Math.mod(i, states.size())).getValue(),
														Urgency__c = urgencies.get(Math.mod(i, urgencies.size())).getValue()));
		}
		insert changeRequests;
		return changeRequests;
	}

}