src/objects/SCOM_Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>&quot;cmdb_ci&quot; from the changerequest.csv</description>
        <label>Application</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval__c</fullName>
        <description>&quot;approval&quot; column from the changerequest.csv</description>
        <label>Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approvers__c</fullName>
        <description>&quot;u_is_approvers&quot; from the changerequest.csv</description>
        <label>Approvers</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>&quot;end_date&quot; column from changerequest.csv</description>
        <label>End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hyperlink__c</fullName>
        <description>&quot;change_request_hyperlink&quot; column from changerequest.csv</description>
        <label>Hyperlink</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opened_At__c</fullName>
        <description>Column &quot;opened_at&quot; from the changerequest.csv.</description>
        <label>Opened At</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opened_By__c</fullName>
        <description>Column &quot;opened_by&quot; from the changerequest.csv.</description>
        <label>Opened By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>&quot;priority&quot; column from the changerequest.csv</description>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Urgent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>&quot;short_description&quot; column from the changerequest.csv</description>
        <label>Short Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>&quot;State&quot; field from the changerequest.csv.</description>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Placeholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Implementation Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergoing Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergoing Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <description>&quot;urgency&quot; column from changerequest.csv</description>
        <label>Urgency</label>
        <picklist>
            <picklistValues>
                <fullName>1 - High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 - Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SCOM Change Request</label>
    <nameField>
        <label>Change Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCOM_Server__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <description>Column &quot;u_application&quot; from the csv. The name of the application hosted on the Server.</description>
        <label>Applications</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Short_Description__c</fullName>
        <description>&quot;short_description&quot; field from the csv</description>
        <label>Short Description</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <label>SCOM Server</label>
    <nameField>
        <label>Server Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_SCOMChangeRequestByServerCtrl.cls
public with sharing class Husky_SCOMChangeRequestByServerCtrl {

    public SCOM_Server__c server {get; private set;}
    public List<String> applications {get; private set;}

    private String serverId;
    private String retUrl;

	public Husky_SCOMChangeRequestByServerCtrl() {
        serverId = ApexPages.currentPage().getParameters().get('serverId');
        retUrl = ApexPages.currentPage().getParameters().get('retURL');
    }

    public List<SCOM_Change_Request__c> changeRequestList {
        get {
            try {
                if(changeRequestList == null || changeRequestList.isEmpty()) {
                    server = [Select Id, Name, Applications__c
                                             From SCOM_Server__c
                                             Where Id = :serverId];
                    applications = server.Applications__c.split(',');
                    changeRequestList = [Select Id, Name, Active__c, Application__c, Approval__c, Approvers__c,
                                                Hyperlink__c, Priority__c, State__c, Urgency__c, Short_Description__c,
                                                Opened_By__c, Opened_At__c, End_Date__c
                                         From SCOM_Change_Request__c
                                         Where Application__c In :applications
                                         Order By End_Date__c DESC NULLS FIRST];
                }
                return changeRequestList;
            } catch (QueryException ex) {
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
                return null;
            }
        }
        private set;
    }
}