src/objects/SCOM_Availability__c.object
<CustomObject>
    <fields>
        <fullName>Polling_Interval__c</fullName>
        <label>Polling Interval</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Server__c</fullName>
        <label>Server</label>
        <referenceTo>SCOM_Server__c</referenceTo>
        <relationshipName>SCOM_Availability</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Up</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Down</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Availability</label>
    <nameField>
        <displayFormat>SAN-{000000000}</displayFormat>
        <label>SCOM Availability Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Availability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SCOM_Change_Request__c.object
<CustomObject>
    <label>SCOM Change Request</label>
    <nameField>
        <label>Change Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCOM_Performance__c.object
<CustomObject>
    <fields>
        <fullName>Avg_Metric_Value__c</fullName>
        <label>Avg Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Metric_Value__c</fullName>
        <label>Current Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Metric_Value__c</fullName>
        <label>Max Metric Value</label>
        <precision>18</precision>
        <scale>9</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Metric__c</fullName>
        <description>The value being measured with this record.</description>
        <label>Metric</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server__c</fullName>
        <label>Server</label>
        <referenceTo>SCOM_Server__c</referenceTo>
        <relationshipName>Performance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Realtime</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Baseline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Performance</label>
    <nameField>
        <displayFormat>SPN-{000000000}</displayFormat>
        <label>SCOM Performance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SCOM_Server__c.object
<CustomObject>
    <fields>
        <fullName>Applications__c</fullName>
        <description>Column &quot;u_application&quot; from the csv. The name of the application hosted on the Server.</description>
        <label>Applications</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Criticality__c</fullName>
        <description>Column &quot;u_cmdb_criticality&quot; from csv.</description>
        <label>Criticality</label>
        <picklist>
            <picklistValues>
                <fullName>(5) Mission Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(4) Business Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(3) Business Important</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(2) Productivity Important</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>(1) Non-Critical</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SCOM Server</label>
    <nameField>
        <label>Server Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCOM Servers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Husky_SCOMDashboardController.cls
public with sharing class Husky_SCOMDashboardController {

	//Both
	public List<String> criticalityCategories {get; private set;}
	public Map<String, List<SCOM_Change_Request__c>> serverToChangeRequestMap {get; private set;}

	//Availability Dashboard
	public Map<String, String> criticalityStatusMap {get; private set;}
	public Map<String, List<SCOM_Availability__c>> availabilityRecordsByCriticalityMap {get; private set;}

	//Performance Dashboard
	public Map<String, String> performanceToStatusMap {get; private set;}
	public Map<String, List<PerformanceWrapper>> 	performanceRecordsByCriticalityMap	{get; private set;}

	private Set<String> serverNames;

	public Husky_SCOMDashboardController() {
		initialize();
		queryAndGroupAvailabilityRecords();
		queryAndGroupPerformanceRecords();
	}

	public void initialize() {
		availabilityRecordsByCriticalityMap = new Map<String, List<SCOM_Availability__c>>();
		performanceRecordsByCriticalityMap = new Map<String, List<PerformanceWrapper>>();
		performanceToStatusMap = new Map<String, String>();
		criticalityStatusMap = new Map<String, String>();
		criticalityCategories = new List<String>();
		serverNames = new Set<String>();
		populateCriticalityStatusMap();
	}

	private void populateCriticalityStatusMap() {
		Schema.DescribeFieldResult fieldResult =
			SCOM_Server__c.Criticality__c.getDescribe();
		List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

		for( Schema.PicklistEntry f : ple) {
			criticalityCategories.add(f.getLabel().substringAfter(' '));
			criticalityStatusMap.put(f.getLabel().substringAfter(' '), 'Up');
			performanceToStatusMap.put(f.getLabel().substringAfter(' ') + Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU, Husky_SCOMUtilities.PERFORMANCE_GREEN);
			performanceToStatusMap.put(f.getLabel().substringAfter(' ') + Husky_SCOMUtilities.PERFORMANCE_METRIC_MEMORY, Husky_SCOMUtilities.PERFORMANCE_GREEN);
			availabilityRecordsByCriticalityMap.put(f.getLabel().substringAfter(' '), new List<SCOM_Availability__c>());
			performanceRecordsByCriticalityMap.put(f.getLabel().substringAfter(' '), new List<PerformanceWrapper>());
		}
	}

	private void queryAndGroupAvailabilityRecords() {
		List<SCOM_Availability__c> availabilityList = [Select Id, Name, Polling_Interval__c, Server__c,
														      Server__r.Name, Server__r.Applications__c, Status__c,
														      Server__r.Criticality__c, Server__r.Data_Center__c
													   From SCOM_Availability__c
													   Order By Status__c Desc];
		for(SCOM_Availability__c availability : availabilityList) {
			serverNames.add(availability.Server__c);
			if(availability.Server__r.Name == 'CGWSCOM350PD') continue;
          
            String key = availability.Server__r.Criticality__c == null ? 'Not Specified' : availability.Server__r.Criticality__c.substringAfter(' ');
            if(availabilityRecordsByCriticalityMap.containsKey(key)){
				availabilityRecordsByCriticalityMap.get(key).add(availability);
            } else {
				availabilityRecordsByCriticalityMap.put(key, new List<SCOM_Availability__c>{availability});
			}

			if(availability.Status__c == 'Down') criticalityStatusMap.put(key, availability.Status__c);
		}
	}

	private void queryAndGroupPerformanceRecords() {
		List<SCOM_Performance__c> performanceList = Database.query(Husky_SCOMUtilities.PERFORMANCE_LIST_QUERY_STRING);
		Map<String, PerformanceWrapper> performanceMergeMap = new Map<String, PerformanceWrapper>();
		for (SCOM_Performance__c performanceRecord : performanceList) {
			String key = performanceRecord.Server__r.Criticality__c + performanceRecord.Server__c;
			if (performanceMergeMap.containsKey(key))
				performanceMergeMap.get(key).addPerformanceValues(performanceRecord);
			else performanceMergeMap.put(key, new PerformanceWrapper(performanceRecord));
		}
		buildPerformanceRecordsByCriticalityMap(performanceMergeMap);
		sortPerformanceLists();
	}

	private void buildPerformanceRecordsByCriticalityMap(Map<String, PerformanceWrapper> performanceMergeMap) {
		//performanceRecordsByCriticalityMap.clear();
		for (PerformanceWrapper performanceWrapper : performanceMergeMap.values()) {
			String key = performanceWrapper.server.Criticality__c == null ? 'Not Specified' : performanceWrapper.server.Criticality__c.substringAfter(' ');
			if (performanceWrapper.server.Criticality__c <> null && performanceRecordsByCriticalityMap.containsKey(key)) {
				performanceRecordsByCriticalityMap.get(key).add(performanceWrapper);
			} else {
				List<PerformanceWrapper> tmpList = new List<PerformanceWrapper>();
				tmpList.add(performanceWrapper);
				performanceRecordsByCriticalityMap.put(key, tmpList);
			}
			setPerformanceCriticalityStatus(key, performanceWrapper);
		}
	}

	private void sortPerformanceLists() {
		for(String criticality : criticalityCategories) {
			performanceRecordsByCriticalityMap.get(criticality).sort();
		}
	}

	private void setPerformanceCriticalityStatus(String key, PerformanceWrapper performanceWrapper) {
		String cpuKey = key + Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU;
		String memKey = key + Husky_SCOMUtilities.PERFORMANCE_METRIC_MEMORY;
		if (performanceWrapper.getCPUPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_ORANGE
			&& performanceToStatusMap.get(cpuKey) != Husky_SCOMUtilities.PERFORMANCE_RED)
			performanceToStatusMap.put(cpuKey, Husky_SCOMUtilities.PERFORMANCE_ORANGE);
		else if (performanceWrapper.getCPUPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_RED)
			performanceToStatusMap.put(cpuKey, Husky_SCOMUtilities.PERFORMANCE_RED);
		if (performanceWrapper.getMemPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_ORANGE
			&& performanceToStatusMap.get(memKey) != Husky_SCOMUtilities.PERFORMANCE_RED)
			performanceToStatusMap.put(memKey, Husky_SCOMUtilities.PERFORMANCE_ORANGE);
		else if (performanceWrapper.getMemPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_RED)
			performanceToStatusMap.put(memKey, Husky_SCOMUtilities.PERFORMANCE_RED);
	}

	public String getPerformanceMetricCPU() {
		return Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU;
	}

	public String getPerformanceMetricMEM() {
		return Husky_SCOMUtilities.PERFORMANCE_METRIC_MEMORY;
	}

	public String getGreen() {
		return Husky_SCOMUtilities.PERFORMANCE_GREEN;
	}

	public String getOrange() {
		return Husky_SCOMUtilities.PERFORMANCE_ORANGE;
	}

	public String getRed() {
		return Husky_SCOMUtilities.PERFORMANCE_RED;
	}

	public class PerformanceWrapper implements Comparable {

		public SCOM_Server__c server {get; private set;}
		public Double cpuAvg 		{get; private set;}
		public Double cpuThreshold	{get; private set;}
		public Double cpuActual		{get; private set;}
		public Double memAvg		{get; private set;}
		public Double memThreshold	{get; private set;}
		public Double memActual		{get; private set;}

		PerformanceWrapper(SCOM_Performance__c performance) {
			this.server = performance.Server__r;
			addPerformanceValues(performance);
		}

		public void addPerformanceValues(SCOM_Performance__c performance) {
			if (performance.Metric__c == Husky_SCOMUtilities.PERFORMANCE_METRIC_CPU)
				setPerformanceValuesForCPU(performance);
			else if (performance.Metric__c == Husky_SCOMUtilities.PERFORMANCE_METRIC_MEMORY)
				setPerformanceValuesForMemory(performance);
		}

		private void setPerformanceValuesForCPU(SCOM_Performance__c performance) {
			if (performance.Type__c == Husky_SCOMUtilities.PERFORMANCE_TYPE_BASELINE) {
				cpuAvg = performance.Avg_Metric_Value__c;
				cpuThreshold = performance.Max_Metric_Value__c;
			} else if (performance.Type__c == Husky_SCOMUtilities.PERFORMANCE_TYPE_REALTIME) {
				cpuActual = performance.Max_Metric_Value__c; //NOTE current values are not stored in Current_Metric_Value__c
			}
		}

		private void setPerformanceValuesForMemory(SCOM_Performance__c performance) {
			if (performance.Type__c == Husky_SCOMUtilities.PERFORMANCE_TYPE_BASELINE) {
				memAvg = performance.Avg_Metric_Value__c;
				memThreshold = performance.Max_Metric_Value__c;
			} else if (performance.Type__c == Husky_SCOMUtilities.PERFORMANCE_TYPE_REALTIME) {
				memActual = performance.Max_Metric_Value__c; //NOTE current values are not stored in Current_Metric_Value__c
			}
		}

		public String getCPUPerformanceStatus() {
			if (cpuAvg != null && cpuThreshold != null && cpuActual != null) {
				if (cpuActual <= cpuAvg) return Husky_SCOMUtilities.PERFORMANCE_GREEN;
				if (cpuActual <= cpuThreshold) return Husky_SCOMUtilities.PERFORMANCE_ORANGE;
				return Husky_SCOMUtilities.PERFORMANCE_RED;
			}
			return null;
		}

		public String getMemPerformanceStatus() {
			if (memAvg != null && memThreshold != null && memActual != null) {
				if (memActual < memAvg) return Husky_SCOMUtilities.PERFORMANCE_GREEN;
				if (memActual < memThreshold) return Husky_SCOMUtilities.PERFORMANCE_ORANGE;
				return Husky_SCOMUtilities.PERFORMANCE_RED;
			}
			return null;
		}

		// Implement the compareTo() method
		public Integer compareTo(Object compareTo) {
			PerformanceWrapper wrapperCompareTo = (PerformanceWrapper) compareTo;
			if (getCPUPerformanceStatus() == wrapperCompareTo.getCPUPerformanceStatus()) {
				if(getMemPerformanceStatus() == wrapperCompareTo.getMemPerformanceStatus()) return 0;
				if(getMemPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_RED && getMemPerformanceStatus() != wrapperCompareTo.getMemPerformanceStatus()) return -1;
				if(getMemPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_ORANGE && wrapperCompareTo.getMemPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_GREEN) return -1;
				return 1;
			} 
			
			if (getCPUPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_RED && getCPUPerformanceStatus() != wrapperCompareTo.getCPUPerformanceStatus()) return -1;
			if(getCPUPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_ORANGE && wrapperCompareTo.getCPUPerformanceStatus() == Husky_SCOMUtilities.PERFORMANCE_GREEN) return -1;
			return 1;
		}

	}
}